### ISSUE TITLE
Armature not recognized in blender, maybe I failed the installation.

### ISSUE THREAD

**Issue by Kyoin** [carlosedubarreto/b3d_mocap_import#1] opened 2021-04-03 14:22 UTC
Hello Carlos, thanks again for your patience,
this is what happens when I import the data:
![1](https://user-images.githubusercontent.com/47851332/113481235-a343c700-9498-11eb-97dc-1d4967ac425f.PNG)
There's a strange piece of armature and some little points moving.
What the hell? xD
How can I fix this?

Thank, thank you.

**Comment by carlosedubarreto** [comment] 2021-04-03 14:35
No problem, my pleasure to be able to help..

Well about the points... its the way I found to make tha import work better than other alternative I've found in other solutions.

Well., it the points are showing, it means that there was a problem in the middle of the import.

I would like to ask you to start a new scene, enable the console
![image](https://user-images.githubusercontent.com/4061130/113481538-809db800-9470-11eb-82c1-c1ec50e013e2.png)

Run again the import and send here what shows up.

If you can, please share the mocap data you are trying to import so I can test here.
And you are using the result from frankmoap right?

**Comment by Kyoin** [comment] 2021-04-03 14:43
Ok this is what it shows:
![2](https://user-images.githubusercontent.com/47851332/113481729-8230a580-949b-11eb-9b83-d97278b9deec.PNG)

[MOCAP_PE_Frankmocap_test_Data.zip](https://github.com/carlosedubarreto/b3d_mocap_import/files/6252751/MOCAP_PE_Frankmocap_test_Data.zip)
And yes I'm using the frankmocap files.

**Comment by carlosedubarreto** [comment] 2021-04-03 14:56
Oh, damn.....
The problem is that your blender is not in English 😅


I tested your files and they worked for me. 
Let me see how I can do to fix this.


If you are anxious to test it, it probably will work if you put your blender in English.

**Comment by Kyoin** [comment] 2021-04-03 14:59
You're a genious it worked with blender in english XDDDD

**Comment by carlosedubarreto** [comment] 2021-04-03 15:06
I'm working on to fix this...
Lol I'm not a genius, but a lazy person LOL.

Now I have a reason to use blender on my own language (to test it so this wont happen with you again) 😊

I'll update you when I fix this.
I'll try to do it today.

**Comment by carlosedubarreto** [comment] 2021-04-03 20:34
I fixed the langiage issue.
Well its working with Brazilian Portuguese 😅, I guess it should work with yours.

I'm having some problems with easymocap, but your are not using it, so you must be fine.

Here is the update, but the best would be to get it from gumroad (its free) so you have the updates, because probably ill be uploading over there.

https://gum.co/mocap_import

[Mocap_PE_data_import_0.3.zip](https://github.com/carlosedubarreto/b3d_mocap_import/files/6253344/Mocap_PE_data_import_0.3.zip)

**Comment by Kyoin** [comment] 2021-04-04 09:06
Thank you so much! Happy Easter!
One last question. Can I work with the generated bvh file for MMD (MikuMikuDance)?
I've tried to translate the bones manually but the result was creepy, I also followed this guide [https://www.deviantart.com/hogarth-mmd/journal/Tutorial-BVH-to-VMD-706240555](url) and this [https://learnmmd.com/http:/learnmmd.com/mmd-bone-reference-charts/](url). Also used LiveAnimation for the conversion but the model dissappear when I load the bvh.
Sorry if I'm asking all of this things, I'm doing my best to achieve what I want but I don't want to stress you anymore ^^".
Just take this as an idea.

Thank you again!

**Comment by carlosedubarreto** [comment] 2021-04-04 09:45
I tried to see the links but they are much more complicated than I could handle at the moment.

But about using the bones created, I wasnt sure if it was really going to work, as I only made the effort to have the bones displaying, but I think I'll have to do a lot of tweaks to make it really usable... (i'm not sure, because I didnt get to the part of testing on real characters)

I think at first you could try to put the animation in a character inside blender using remapping tools like rokoko addon that is free. (or autorig pro but its paid)

If the motions works nice, then you could go to the part of exporting it to use in MMD.
If not, maybe some tweaks using bone constraints could be usefull.

Well, I'm telling this if you want to advance on it sooner. Because I'll get to the point od testing it in characters, but probably it will take longer, because I still have to make the code stable, and that will consume me a lot of time.

And please dont bother to ask, I'll be glad to help if I can, and if I cant, at least i'll try to point you in the direction I think its the best one..

And thanks for all the attention and testing and all 😍

**Comment by Kyoin** [comment] 2021-04-04 10:34
Thank you for all your hard work.
I tried with rokoko but I failed, it's the same thing of the bones renamer for MMD. The model gets distorted.
Oh well! I think I'll wait for your magic work. It's a pleasure for me to test what you do and study.

**Comment by carlosedubarreto** [comment] 2021-04-04 14:47
Hum. I see.
Maybe I'll have to fix this problem first.
I'll close this issue, and open one about the problem on the retargeting.

Probably this week I'll work on it.

**Closed by carlosedubarreto** 2021-04-04 14:47 UTC
Labels: bug

**Comment by carlosedubarreto** [comment] 2021-04-09 13:11
Hello @Kyoin , I've finished working on the better skeleton.
Now your are able to use it to retargetting.

you can get here on this github or download the zip from 
[https://gumroad.com/l/mocap_import](https://gumroad.com/l/mocap_import)

**Comment by Kyoin** [comment] 2021-04-09 14:15
@carlosedubarreto , you did a great job! The only think that now disappoints me it's frankmocap itself. It is not so accurate already and sometimes it makes me so angry lol. Here a few tips that I noticed for installing beta 0.5:
1 - You MUST have before installed vs. 0.1 of the addon, then you install vs 0.5
2 - Run Blender as administrator or the libraries will not install.

Thank you again!

**Comment by carlosedubarreto** [comment] 2021-04-09 14:19
Thanks for the tip.
I also have some problems when installing, but what I do is, remove the addon, close blender, open again and install the new version.

I dont know why it happens. I'll hve to take sometime to tackle this issue.

About the frankmocap pose estimation, maybe you could try also VIBE, and try to get the best from each one of them..

I think vibe is even easier to install, in case you didnt already (i really dont remember 😅)

**Comment by Kyoin** [comment] 2021-04-10 10:09
Hi Carlos. happy weekend!
I'm still struggling with the bones renamer ( now i'm using vibe) and
keeping creating monster-armatures for my poor mmd models lol.
But I'm sure a solution exist. I'm using rokoko retag metod.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno ven 9 apr 2021 alle ore 16:20 Carlos Barreto <
***@***.***> ha scritto:

**Comment by carlosedubarreto** [comment] 2021-04-10 10:24
I'm using autorig pro and its working pretty  nice.

If you have it, you can use this rmap data (for autorig pro)
[MOCAP_IMPORT_ARP_remap_preset.zip](https://github.com/carlosedubarreto/b3d_mocap_import/files/6289658/MOCAP_IMPORT_ARP_remap_preset.zip)


and happy weekend for you too

**Comment by Kyoin** [comment] 2021-04-10 11:16
How do I use the remap data? :( so noob I am

**Comment by carlosedubarreto** [comment] 2021-04-10 11:57
If you use have autorig, here is the link to the docs with a video 
[http://www.lucky3d.fr/auto-rig-pro/doc/remap_doc.html](http://www.lucky3d.fr/auto-rig-pro/doc/remap_doc.html)

But... if you didnt need it untli now, probably just for remap you could use other options(like the rokoko you are trying).

Let me finish some ajustments I'm making on the addon, then, I'll do a test with rokoko addon and share with you the process.

I'm just not sure that I'll be able to do it today...

**Comment by Kyoin** [comment] 2021-04-10 12:20
Ok i'll wait for the adjustments but i'll will keep experimenting with autorig too. We'll see what comes out!

And don't worry take your time ^^

**Comment by carlosedubarreto** [comment] 2021-04-15 08:32
Hello @Kyoin .
Finally I finished some retation tweaks to get a better mocap data.
And then I went to try to do some retargetting.

Here is a test I've done with Rokoko Studio Live. You can download the remap preset for autorig pro or rokoko (i already added on gumroad, but I'll then here at github too

https://user-images.githubusercontent.com/4061130/114839228-e876cb80-9dab-11eb-8fd7-01d07117fc18.mp4
